tomcat.port=8080
tomcat.username=tcuser
tomcat.password=tcuser
tomcat.database.host=localhost
tomcat.database.port=3306
tomcat.database.name=scadalts
tomcat.database.username=root
tomcat.database.password=root